import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import { createVisualFieldRegistry } from "../src/live-pdf-studio/visual-field-registry.js";
import { validateVisualDraft } from "../src/live-pdf-studio/visual-validation.js";
import { renderVisualReferenceEditor } from "../src/live-pdf-studio/visual-controls.js";
const root = path.resolve(import.meta.dirname, "..");
const fixture = async () => JSON.parse(await fs.readFile(path.join(root,"src/data/paragon-live-pdf-studio.json"),"utf8"));

test("visual registry locks 95 bindings across logos cuts and footer", async () => { const draft=await fixture(); const registry=createVisualFieldRegistry(draft); assert.equal(registry.fields.length,95); assert.equal(registry.bySection.logos.length,43); assert.equal(registry.bySection.cuts.length,42); assert.equal(registry.bySection.footer.length,10); });
test("visual registry preserves 15 references and seven product images", async () => { const draft=await fixture(); const registry=createVisualFieldRegistry(draft); assert.equal(registry.fields.filter(f=>f.key.endsWith('.visible')).length,15); assert.equal(registry.bySection.cuts.filter(f=>f.key.endsWith('.visible')).length,7); });
test("canonical visual draft validates complete", async () => { const live=await fixture(); const registry=createVisualFieldRegistry(live); const result=validateVisualDraft({draft:structuredClone(live),liveDocument:live,registry}); assert.equal(result.issues.length,0); assert.equal(result.statuses.logos,'Complete'); });
test("visual validation rejects fit zoom focus and empty visible alt", async () => { const live=await fixture(); const draft=structuredClone(live); draft.header.brandMark.fit='stretch'; draft.header.brandMark.zoom=3; draft.header.brandMark.focusX=-1; draft.header.brandMark.alt=''; const result=validateVisualDraft({draft,liveDocument:live,registry:createVisualFieldRegistry(draft)}); assert.ok(result.issues.length>=4); assert.equal(result.statuses.logos,'Validation error'); });
test("footer treatment ranges remain validated", async () => { const live=await fixture(); const draft=structuredClone(live); draft.footer.broll.opacity=2; const result=validateVisualDraft({draft,liveDocument:live,registry:createVisualFieldRegistry(draft)}); assert.equal(result.statuses.footer,'Validation error'); });
test("visual editor renders asset id drag stage and canonical controls", async () => { const draft=await fixture(); const registry=createVisualFieldRegistry(draft); const markup=renderVisualReferenceEditor({draft,reference:draft.header.brandMark,prefix:'header.brandMark',label:'Brand mark',fields:registry.bySection.logos.filter(f=>f.key.startsWith('header.brandMark'))}); assert.match(markup,/data-visual-stage="header.brandMark"/); assert.match(markup,/Asset assignment is read-only until Phase 3.5/); assert.match(markup,/data-editor-field="header.brandMark.zoom"/); });
test("Tri Tip remains single offer and footer focus Y remains 100", async () => { const draft=await fixture(); assert.equal(draft.specials.find(s=>s.id==='tri-tip').offerMode,'single-offer'); assert.equal(draft.footer.broll.focusY,100); });
test("Studio integration exposes visual controls without repository writes", async () => { const [main,controller,styles,pkg]=await Promise.all(['src/live-pdf-studio/main.js','src/live-pdf-studio/editor-controller.js','src/live-pdf-studio/styles.css','package.json'].map(p=>fs.readFile(path.join(root,p),'utf8'))); assert.match(main,/visualBindings: 95/); assert.match(controller,/handleWheel/); assert.match(controller,/handlePointerDown/); assert.match(styles,/visual-stage/); assert.match(JSON.parse(pkg).scripts['test:specials:contracts'],/live-pdf-studio-visual-controls/); assert.doesNotMatch(main+controller,/git push|gh workflow|localStorage\.setItem/i); });
